name: 'AWS Lambda Update Action'
author: 'Kazi Manzur Rashid <kazimanzurrashid@gmail.com>'
branding:
  color: 'orange'
  icon: 'upload'
description: 'Updates the specified lambda'
inputs:
  zip-file:
    required: true
    description: 'The zip file location'
  lambda-name:
    required: false
    description: 'Optional, if not specified, it uses the file base name as function name'
  AWS_REGION:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
  AWS_ACCESS_KEY_ID:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
  AWS_SECRET_ACCESS_KEY:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
  AWS_SESSION_TOKEN:
    description: 'Optional if not specified fallbacks to environment variable'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
